using System;
using System.IO;
using System.Linq;
using System.Reflection;

namespace cabinet.CodeGen;

/// <summary>
/// Contains logic for writing a cabinet file.
/// </summary>
internal static class CabinetFileWriter
{
  private const string SHELL =
    """
    // -- Generated by Cabinet {0}
    // -- https://github.com/minisbett/cabinet
    //
    // Assembly: {1}
    //     Date: {2}

    #include <stdint.h>
    #include <stdbool.h>

    {3}
    """;

  /// <summary>
  /// Generates the source for the specified cabinet and writes it to the specified file.
  /// </summary>
  public static void Write(string filePath, Cabinet cabinet, string assemblyFile)
  {
    string version = Assembly.GetExecutingAssembly().GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion.Split('+')
#if RELEASE
      [0];
#else
      [1];
#endif

    string timestamp = DateTimeOffset.Now.ToString("yyyy-MM-dd HH:mm:ss K");

    string enumsStr = string.Join("\n\n", cabinet.Enums.Select(x => x.ToString()));
    string structsStr = string.Join("\n\n", cabinet.Structs.Select(x => x.ToString()));
    string functionsStr = string.Join("\n", cabinet.Functions.Select(x => x.ToString()));

    string content = string.Format(SHELL, version, assemblyFile, timestamp, string.Join("\n\n", [enumsStr, structsStr, functionsStr]));
    File.WriteAllText(filePath, content);
  }
}
